name: XMod
version: "2.95"
license: "GPL-2.0-or-later"
date: 2025-07-10
description: |
    Crossed Modules and Cat1-Groups

authors:
    - name: Chris Wensley
      url: https://github.com/cdwensley
    - name: Murat Alp
      url: mailto:muratalp@nigde.edu.tr
    - name: Alper Odabas
      url: mailto:aodabas@ogu.edu.tr
    - name: Enver Onder Uslu

maintainers:
    - name: Chris Wensley
      url: https://github.com/cdwensley

GAP: ">=4.11.0"

needed-pkgs:
    - name: "utils"
      version: ">= 0.81"
      url: "https://gap-packages.github.io/utils"
    - name: "groupoids"
      version: ">= 1.77"
      url: "https://gap-packages.github.io/groupoids/"
    - name: "HAP"
      version: ">= 1.29"
      url: "https://gap-packages.github.io/hap"
    - name: "AutPGrp"
      version: ">= 1.10.2"
      url: "https://gap-packages.github.io/autpgrp/"
    - name: "SmallGrp"
      version: ">= 1.4.2"
      url: "https://gap-packages.github.io/smallgrp/"

www: https://gap-packages.github.io/xmod/
readme: README.md
packageinfo: https://gap-packages.github.io/xmod/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/xmod/releases/download/v2.95/XMod-2.95.tar.gz

abstract: |
    The <span class="pkgname">XMod</span> package provides a collection   of functions for computing with crossed modules and cat1-groups, their derivations and sections, morphisms of these structures, and higher-dimensional generalisations.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    crossed module, cat1-group, derivation, section, actor, crossed square.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>WAOU25</span>]   <b class='BibAuthor'>Wensley, C., Alp, M., Odabas, A. and Uslu, E. O.</b>,
     <i class='BibTitle'>XMod, Crossed Modules and Cat1-Groups,
             Version 2.95</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/xmod/">https://gap-packages.github.io/xmod/</a></span>.
    </p>
    

bibtex: |
    @misc{ XMod,
      author =           {Wensley, C. and Alp, M. and Odabas, A. and Uslu, E. O.},
      title =            {{XMod},          {Crossed          Modules         and
                          Cat1\texttt{\symbol{45}}Groups}, {V}ersion 2.95},
      month =            {Jul},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href           {https://gap-packages.github.io/xmod/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{xmod/}}},
      keywords =         {crossed     module;     cat1\texttt{\symbol{45}}group;
                          derivation; section; actor; crossed square},
      printedkey =       {WAOU25}
    }

