name: XMod
version: "2.84"
license: "GPL-2.0-or-later"
date: 2021-11-15
description: |
    Crossed Modules and Cat1-Groups

authors:
    - name: Chris Wensley
      url: https://github.com/cdwensley
    - name: Murat Alp
      url: mailto:muratalp@nigde.edu.tr
    - name: Alper Odabas
      url: mailto:aodabas@ogu.edu.tr
    - name: Enver Onder Uslu

maintainers:
    - name: Chris Wensley
      url: https://github.com/cdwensley

GAP: ">=4.11.0"

needed-pkgs:
    - name: "Utils"
      version: ">= 0.69"
      url: "https://gap-packages.github.io/utils"
    - name: "groupoids"
      version: ">= 1.68"
      url: "https://gap-packages.github.io/groupoids/"
    - name: "Hap"
      version: ">= 1.25"
      url: "https://gap-packages.github.io/hap"
    - name: "AutPGrp"
      version: ">= 1.10.2"
      url: "https://gap-packages.github.io/autpgrp/"
    - name: "SmallGrp"
      version: ">= 1.4.1"
      url: "https://gap-packages.github.io/smallgrp/"

suggested-pkgs:
    - name: "AutoDoc"
      version: ">=2019.09.04"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "GAPDoc"
      version: ">= 1.6.3"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/xmod/
readme: README.md
packageinfo: https://gap-packages.github.io/xmod/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/xmod/releases/download/v2.84/XMod-2.84.tar.gz

abstract: |
    The <span class="pkgname">XMod</span> package provides a collection   of functions for computing with crossed modules and cat1-groups, their derivations and sections, morphisms of these structures, and higher-dimensional generalisations.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    crossed module, cat1-group, derivation, section, actor, crossed square.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>WAOU21</span>]   <b class='BibAuthor'>Wensley, C., Alp, M., Odabas, A. and Uslu, E. O.</b>,
     <i class='BibTitle'>XMod, Crossed Modules and Cat1-Groups,
             Version 2.84</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/xmod/">https://gap-packages.github.io/xmod/</a></span>.
    </p>
    

bibtex: |
    @misc{ XMod2.84,
      author =           {Wensley, C. and Alp, M. and Odabas, A. and Uslu, E. O.},
      title =            {{XMod},  Crossed  Modules  and  Cat1-Groups, {V}ersion
                          2.84},
      month =            {Nov},
      year =             {2021},
      note =             {Refereed GAP package},
      howpublished =     {\href           {https://gap-packages.github.io/xmod/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{xmod/}}},
      keywords =         {crossed   module;   cat1-group;  derivation;  section;
                          actor; crossed square},
      printedkey =       {WAOU21}
    }

