# XMod, chapter 10
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("xmod10.tst");

# doc/gpd2obj.xml:68-87
gap> CX4 := SinglePiecePreXModWithObjects( X4, [-6,-5,-4], false );
single piece precrossed module with objects
  source groupoid:
    single piece groupoid: < a4, [ -6, -5, -4 ] >
  and range groupoid:
    single piece groupoid: < s4, [ -6, -5, -4 ] >
gap> SetName( CX4, "CX4" );
gap> Ca4 := Source( CX4 );;  SetName( Ca4, "Ca4" );
gap> Cs4 := Range( CX4 );;  SetName( Cs4, "Cs4" );
gap> DX4 := SinglePiecePreXModWithObjects( X4, [-9,-8,-7], true );
single piece precrossed module with objects
  source groupoid:
    homogeneous, discrete groupoid: < a4, [ -9, -8, -7 ] >
  and range groupoid:
    single piece groupoid: < s4, [ -9, -8, -7 ] >
gap> SetName( DX4, "DX4" );
gap> Da4 := Source( DX4 );;  SetName( Da4, "Da4" );
gap> Ds4 := Range( DX4 );;  SetName( Ds4, "Ds4" );

# doc/gpd2obj.xml:102-107
gap> Set( KnownPropertiesOfObject( CX4 ) );
[ "CanEasilyCompareElements", "CanEasilySortElements", "IsAssociative", 
  "IsDuplicateFree", "IsGeneratorsOfSemigroup", "IsPreXModWithObjects", 
  "IsSinglePieceDomain", "IsXModWithObjects" ]

# doc/gpd2obj.xml:123-130
gap> IsPermPreXModWithObjects( CX4 );
true
gap> IsPcPreXModWithObjects( CX4 );
false
gap> IsFpPreXModWithObjects( CX4 );
false

# doc/gpd2obj.xml:156-186
gap> Root2dGroup( CX4 );
[a4->s4]
gap> actC := XModAction( CX4 );;
gap> Size( Range( actC ) );
20736
gap> r1 := Arrow( Cs4, (1,2,3,4), -4, -5 );;
gap> ir1 := ImageElm( actC, r1 );
[groupoid homomorphism : Ca4 -> Ca4
[ [ [(1,2,3) : -6 -> -6], [(2,3,4) : -6 -> -6], [() : -6 -> -5], 
      [() : -6 -> -4] ], 
  [ [(2,3,4) : -4 -> -4], [(1,3,4) : -4 -> -4], [() : -4 -> -6], 
      [() : -4 -> -5] ] ] : 0 -> 0]
gap> s1 := Arrow( Ca4, (1,2,4), -5, -5 );;
gap> ##  calculate s1^r1 
gap> ims1 := ImageElmXModAction( CX4, s1, r1 );
[(1,2,3) : -6 -> -6]
gap> ## repeat using DX4
gap> actD := XModAction( DX4 );;
gap> SetName( Range( actD ), "autD" );
gap> Size( Range( actD ) );
82944
gap> r2 := Arrow( Ds4, (1,2,3,4), -7, -8 );;
gap> ImageElm( actD, r2 );
[groupoid homomorphism : Da4 -> Da4
 : 0 -> 0]
gap> s2 := Arrow( Da4, (1,2,4), -8, -8 );;
gap> ##  calculate s2^r2 
gap> ims2 := ImageElmXModAction( DX4, s2, r2 );
[(1,2,3) : -9 -> -9]

#
gap> STOP_TEST("xmod10.tst", 1);
