# XMod, chapter 13
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("xmod13.tst");

# doc/hap.xml:42-47
gap> H12 := SmallCatOneGroup( 12, 4, 3 );
Cat-1-group with underlying group Group( [ f1, f2, f3 ] ) . 
gap> C12 := SmallCat1Group( 12, 4, 3 );
[Group( [ f1, f2, f3 ] )=>Group( [ f1, f2, <identity> of ... ] )]

# doc/hap.xml:60-67
gap> C12 := CatOneGroupToXMod( H12 );    
[Group( [ f1, f2, f3 ] )=>Group( [ f1, f2, <identity> of ... ] )]
gap> C18 := Cat1Select( 18, 4, 3 );
[(C3 x C3) : C2=>Group( [ f1, <identity> of ..., f3 ] )]
gap> H18 := Cat1GroupToHAP( C18 ); 
Cat-1-group with underlying group (C3 x C3) : C2 . 

# doc/hap.xml:81-86
gap> IdCatOneGroup( H18 ); 
[ 18, 4, 4 ]
gap> IdCat1Group( C18 ); 
[ 18, 4, 4 ]

#
gap> STOP_TEST("xmod13.tst", 1);
